In [22]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [34]:
import numpy as np

In [24]:
np.__version__

'1.19.5'

In [1]:
class Chromosome:
    def __init__(self, size=1):
        self._chromosome = np.random.rand(size)

In [35]:
class Population:
    def __init__(self, size=100, n_items=8):
        self._size = size
        self._n_items = n_items
        
    def populate(self):
        n_row = self._size
        n_col = self._n_items
        #self._pop = np.random.rand(n_row, n_col)
        np.full
        
    @property
    def pop(self):
        if isinstance(self._pop, np.ndarray):
            return self._pop
        else:
            raise Exception('empty poopulation')
        
    @property
    def fitness(self):
        return self._fitness_func
    
    @fitness.setter
    def fitness(self, func):
        self._fitness_func = func
    
    def fit(self):
        self._values = np.apply_along_axis(self.fitness, 1, self.pop)

In [36]:
p = Population(100, 8)

In [37]:
p.populate()

In [38]:
p.pop

array([[9.95364878e-01, 2.84094592e-01, 2.92049235e-01, 6.17469907e-01,
        8.32660687e-01, 8.27094859e-01, 2.64224681e-01, 3.16005939e-01],
       [9.30560059e-01, 1.47083295e-01, 7.57301481e-01, 7.26022714e-01,
        7.66027122e-01, 4.69757471e-01, 6.66518081e-01, 7.58237429e-01],
       [8.52868124e-01, 5.17488740e-01, 5.00224237e-01, 7.68380579e-01,
        3.87162359e-01, 1.30589296e-01, 5.84743052e-01, 7.59063319e-02],
       [2.24345557e-02, 6.10632386e-01, 1.07263861e-01, 4.44606697e-02,
        6.33746637e-01, 3.92869498e-01, 7.28868787e-01, 6.15152947e-01],
       [2.95231439e-01, 9.62578892e-01, 4.22413590e-01, 1.06736921e-01,
        8.89193654e-01, 6.89729052e-01, 9.88467603e-01, 6.99507097e-01],
       [8.96939204e-01, 1.56430737e-01, 9.77075845e-01, 5.61575984e-02,
        8.20916298e-01, 8.59174818e-01, 4.07006163e-01, 3.40838007e-01],
       [4.18667104e-01, 7.41333864e-01, 4.97148933e-01, 9.28500175e-01,
        8.07393705e-01, 8.59830874e-01, 8.41529968e-01, 5.

In [47]:
def f(a):
    return np.sum(a)

In [48]:
p.fitness = f

In [49]:
p.fit()

In [50]:
p.pop

array([[9.95364878e-01, 2.84094592e-01, 2.92049235e-01, 6.17469907e-01,
        8.32660687e-01, 8.27094859e-01, 2.64224681e-01, 3.16005939e-01],
       [9.30560059e-01, 1.47083295e-01, 7.57301481e-01, 7.26022714e-01,
        7.66027122e-01, 4.69757471e-01, 6.66518081e-01, 7.58237429e-01],
       [8.52868124e-01, 5.17488740e-01, 5.00224237e-01, 7.68380579e-01,
        3.87162359e-01, 1.30589296e-01, 5.84743052e-01, 7.59063319e-02],
       [2.24345557e-02, 6.10632386e-01, 1.07263861e-01, 4.44606697e-02,
        6.33746637e-01, 3.92869498e-01, 7.28868787e-01, 6.15152947e-01],
       [2.95231439e-01, 9.62578892e-01, 4.22413590e-01, 1.06736921e-01,
        8.89193654e-01, 6.89729052e-01, 9.88467603e-01, 6.99507097e-01],
       [8.96939204e-01, 1.56430737e-01, 9.77075845e-01, 5.61575984e-02,
        8.20916298e-01, 8.59174818e-01, 4.07006163e-01, 3.40838007e-01],
       [4.18667104e-01, 7.41333864e-01, 4.97148933e-01, 9.28500175e-01,
        8.07393705e-01, 8.59830874e-01, 8.41529968e-01, 5.

In [51]:
p._values

array([4.42896478, 5.22150765, 3.81736272, 3.15542934, 5.05385825,
       4.51453867, 5.15033779, 4.32315065, 3.59999075, 3.21621705,
       5.5907495 , 3.53240289, 5.64182774, 4.52358549, 2.37945495,
       2.41478728, 4.4343284 , 4.81785137, 3.72920567, 3.63946586,
       3.90776322, 6.04960236, 4.76509129, 4.2295944 , 3.64667848,
       3.60122323, 4.80247946, 5.59307259, 4.21371816, 4.54299325,
       4.20009346, 4.33000132, 4.37370139, 4.29526625, 3.0136667 ,
       3.04427045, 4.15470653, 3.43721351, 5.25130473, 4.65540718,
       4.8303059 , 3.77464113, 3.47897419, 3.38694969, 2.46481196,
       4.08461637, 3.2812512 , 3.40202689, 3.0090477 , 3.52861252,
       3.94886407, 3.65489695, 4.684343  , 4.09121773, 3.46201151,
       2.9244167 , 2.94718954, 3.49533263, 3.68627196, 3.88558255,
       2.97979596, 5.39944993, 3.21319293, 2.98995899, 3.37670887,
       2.13567579, 2.73446574, 3.11672819, 4.71786491, 3.74760599,
       3.97061277, 4.96438431, 4.76116667, 3.458634  , 4.63904

In [6]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
def f(a):
    return np.sum(a)

np.apply_along_axis(f, 1, a)

array([ 6, 15, 24])

In [52]:
b = {'a':1, 'b':3}

In [53]:
a = np.array([[b,b,b],[b,b,b]])

In [54]:
a

array([[{'a': 1, 'b': 3}, {'a': 1, 'b': 3}, {'a': 1, 'b': 3}],
       [{'a': 1, 'b': 3}, {'a': 1, 'b': 3}, {'a': 1, 'b': 3}]],
      dtype=object)